'use client'

import Link from 'next/link'
import { useMemo, useState, type FormEvent } from 'react'
import { CalendarDays, ChefHat, FolderTree, MapPin, Pencil, Plus, Settings2, Trash2, X } from 'lucide-react'
import { menu as initialMenu, categories, type MenuItem } from '@/lib/data'

const cards = [['Menu items', String(initialMenu.length), ChefHat], ['Bookings', 'API ready', CalendarDays], ['Locations', 'Config ready', MapPin], ['Content', 'API ready', Settings2]] as const

export default function Admin() {
  const [items, setItems] = useState(initialMenu)
  const [editing, setEditing] = useState<MenuItem | null>(null)
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({ name: '', category: categories[0]?.id ?? '', price: '' })
  const visibleItems = useMemo(() => items.slice(0, 12), [items])
  const openAdd = () => { setEditing(null); setForm({ name: '', category: categories[0]?.id ?? '', price: '' }); setShowForm(true) }
  const openEdit = (item: MenuItem) => { setEditing(item); setForm({ name: item.name, category: item.category, price: String(item.price) }); setShowForm(true) }
  const saveItem = (event: FormEvent) => { event.preventDefault(); const name = form.name.trim(); const price = Number(form.price); if (!name || !Number.isFinite(price) || price <= 0) return; if (editing) setItems((current) => current.map((item) => item.id === editing.id ? { ...item, name, category: form.category, price } : item)); else setItems((current) => [{ id: `draft-${Date.now()}`, name, category: form.category, price, vegetarian: true, available: true, image: categories.find((c) => c.id === form.category)?.image ?? '/images/categories/dosa.jpg' }, ...current]); setShowForm(false) }
  const deleteItem = (item: MenuItem) => { if (window.confirm(`Delete ${item.name}?`)) setItems((current) => current.filter((entry) => entry.id !== item.id)) }
  const toggleAvailability = (item: MenuItem) => setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, available: !entry.available } : entry))

  return <main className="min-h-screen bg-muted/40"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Admin portal foundation</p><h1 className="mt-2 text-4xl font-black tracking-tight">Restaurant operations</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">UI actions work locally for review; persistence and authentication remain delegated to the backend API.</p></div><Link href="/" className="text-sm font-bold underline">View website</Link></div>
    <section className="mt-8 rounded-3xl border bg-card p-5 sm:p-8"><h2 className="text-xl font-black">Backend authentication handoff</h2><div className="mt-4 flex flex-wrap gap-3"><input aria-label="Admin email" placeholder="Admin email" type="email" className="h-11 rounded-full border bg-background px-4" /><button disabled className="rounded-full border px-4 py-2 text-sm font-bold">Sign in via API</button><span className="self-center text-xs text-muted-foreground">Awaiting coordinated auth endpoint</span></div></section>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border bg-card p-5"><Icon className="text-primary" size={20}/><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{label === 'Menu items' ? items.length : value}</p></div>)}</div>
    <section className="mt-8 rounded-3xl border bg-card p-5 sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-black">Menu management</h2><p className="mt-1 text-sm text-muted-foreground">Add, edit, delete and toggle availability. API calls can replace these local handlers.</p></div><button onClick={openAdd} className="inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><Plus size={16}/> Add dish</button></div>
      {showForm && <form onSubmit={saveItem} className="mt-6 grid gap-3 rounded-2xl border bg-muted/30 p-4 sm:grid-cols-[1.4fr_1fr_.7fr_auto_auto]"><input required aria-label="Dish name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Dish name" className="h-11 rounded-xl border bg-background px-3"/><select aria-label="Dish category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="h-11 rounded-xl border bg-background px-3">{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input required min="1" step="1" aria-label="Dish price" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} placeholder="Price" type="number" className="h-11 rounded-xl border bg-background px-3"/><button type="submit" className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">{editing ? 'Save' : 'Add'}</button><button type="button" onClick={() => setShowForm(false)} aria-label="Close dish form" className="rounded-xl border p-2"><X size={18}/></button></form>}
      <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="pb-3">Dish</th><th className="pb-3">Category</th><th className="pb-3">Price</th><th className="pb-3">Availability</th><th className="pb-3">Actions</th></tr></thead><tbody>{visibleItems.map(item => <tr key={item.id} className="border-b last:border-0"><td className="py-4 font-semibold">{item.name}</td><td className="py-4 text-muted-foreground">{item.category}</td><td className="py-4">₹{item.price}</td><td className="py-4"><button type="button" onClick={() => toggleAvailability(item)} className={`rounded-full px-3 py-1 text-xs font-bold ${item.available ? 'bg-primary/15 text-primary' : 'bg-muted text-muted-foreground'}`}>{item.available ? 'Available' : 'Unavailable'}</button></td><td className="py-4"><div className="flex gap-2"><button onClick={() => openEdit(item)} aria-label={`Edit ${item.name}`} className="rounded-lg border p-2"><Pencil size={15}/></button><button onClick={() => deleteItem(item)} aria-label={`Delete ${item.name}`} className="rounded-lg border p-2 text-destructive"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-3"><section className="rounded-3xl border bg-card p-6"><FolderTree className="text-primary"/><h2 className="mt-4 text-xl font-black">Categories</h2><p className="mt-2 text-sm text-muted-foreground">Create, edit, delete and assign representative category images through the API.</p><p className="mt-4 font-bold">{categories.length} configured</p></section><section className="rounded-3xl border bg-card p-6"><CalendarDays className="text-primary"/><h2 className="mt-4 text-xl font-black">Booking management</h2><p className="mt-2 text-sm text-muted-foreground">GET bookings and PUT booking status once the backend endpoints are connected.</p></section><section className="rounded-3xl border bg-card p-6"><MapPin className="text-primary"/><h2 className="mt-4 text-xl font-black">Locations & content</h2><p className="mt-2 text-sm text-muted-foreground">Manage verified locations and approved site copy through coordinated APIs.</p></section></div>
  </div></main>
}
