'use client'

import Link from 'next/link'
import { CalendarDays, ChefHat, FolderTree, MapPin, Pencil, Plus, Settings2, Trash2 } from 'lucide-react'
import { menu, categories } from '@/lib/data'

const cards = [['Menu items', String(menu.length), ChefHat], ['Bookings', 'API ready', CalendarDays], ['Locations', 'Config ready', MapPin], ['Content', 'API ready', Settings2]] as const

export default function Admin() { return <main className="min-h-screen bg-muted/40"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
  <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Admin portal foundation</p><h1 className="mt-2 text-4xl font-black tracking-tight">Restaurant operations</h1><p className="mt-2 max-w-xl text-sm text-muted-foreground">Authentication and persistence are intentionally delegated to the backend API. No local login or fake security is used here.</p></div><Link href="/" className="text-sm font-bold underline">View website</Link></div>
  <section className="mt-8 rounded-3xl border bg-card p-5 sm:p-8"><h2 className="text-xl font-black">Backend authentication handoff</h2><div className="mt-4 flex flex-wrap gap-3"><input aria-label="Admin email" placeholder="Admin email" type="email" className="h-11 rounded-full border bg-background px-4" /><button disabled className="rounded-full border px-4 py-2 text-sm font-bold">Sign in via API</button><span className="self-center text-xs text-muted-foreground">Awaiting coordinated auth endpoint</span></div></section>
  <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border bg-card p-5"><Icon className="text-primary" size={20}/><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
  <section className="mt-8 rounded-3xl border bg-card p-5 sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-black">Menu management</h2><p className="mt-1 text-sm text-muted-foreground">Edit, add, delete and toggle availability through the backend service layer.</p></div><button className="inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground"><Plus size={16}/> Add dish</button></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="pb-3">Dish</th><th className="pb-3">Category</th><th className="pb-3">Price</th><th className="pb-3">Availability</th><th className="pb-3">Actions</th></tr></thead><tbody>{menu.slice(0, 10).map(item => <tr key={item.id} className="border-b last:border-0"><td className="py-4 font-semibold">{item.name}</td><td className="py-4 text-muted-foreground">{item.category}</td><td className="py-4">₹{item.price}</td><td className="py-4">{item.available ? 'Available' : 'Unavailable'}</td><td className="py-4"><div className="flex gap-2"><button aria-label={`Edit ${item.name}`} className="rounded-lg border p-2"><Pencil size={15}/></button><button aria-label={`Delete ${item.name}`} className="rounded-lg border p-2"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></section>
  <div className="mt-8 grid gap-6 lg:grid-cols-3"><section className="rounded-3xl border bg-card p-6"><FolderTree className="text-primary"/><h2 className="mt-4 text-xl font-black">Categories</h2><p className="mt-2 text-sm text-muted-foreground">Create, edit, delete and assign representative category images.</p><p className="mt-4 font-bold">{categories.length} configured</p></section><section className="rounded-3xl border bg-card p-6"><CalendarDays className="text-primary"/><h2 className="mt-4 text-xl font-black">Booking management</h2><p className="mt-2 text-sm text-muted-foreground">GET bookings and PUT booking status once the backend endpoints are connected.</p></section><section className="rounded-3xl border bg-card p-6"><MapPin className="text-primary"/><h2 className="mt-4 text-xl font-black">Locations & content</h2><p className="mt-2 text-sm text-muted-foreground">Manage verified locations and approved site copy through coordinated APIs.</p></section></div>
</div></main> }
