'use client'

import { useMemo, useState } from 'react'
import { Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Leaf } from 'lucide-react'
import { categories, formatPrice, menu, type MenuItem } from '@/lib/data'
import { CategoryImage, Shell } from '@/components/site-shell'

export default function MenuPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const [cart, setCart] = useState<Record<string, number>>({})
  const filtered = useMemo(() => menu.filter((item) => {
    const matchesCategory = category === 'all' || item.category === category
    return matchesCategory && `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())
  }), [category, query])
  const updateCart = (item: MenuItem, delta: number) => setCart((current) => { const count = Math.max(0, (current[item.id] ?? 0) + delta); const next = { ...current }; if (count) next[item.id] = count; else delete next[item.id]; return next })
  const cartCount = Object.values(cart).reduce((sum, count) => sum + count, 0)

  return <Shell><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 md:py-20">
    <p className="text-sm font-bold uppercase tracking-[.2em] text-primary">The menu</p>
    <div className="mt-3 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><h1 className="max-w-2xl text-5xl font-black tracking-tight sm:text-7xl">Made fresh, <span className="text-primary">worth sharing.</span></h1><p className="mt-5 max-w-xl text-muted-foreground">Browse the full menu and build your order list with simple add, remove and quantity controls.</p></div>{cartCount > 0 && <div className="flex items-center gap-3 rounded-2xl border bg-card p-3 shadow-sm"><ShoppingBag className="size-5 text-primary"/><span className="text-sm font-bold">{cartCount} added</span><a href="/order" className="rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Review order</a></div>}</div>
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search dishes</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={18}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search dosa, idli, coffee..." className="h-12 w-full rounded-full border bg-background pl-11 pr-4 outline-none focus:ring-2 focus:ring-primary" /></label><button type="button" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border px-5 text-sm font-semibold"><SlidersHorizontal size={16}/> Dietary options</button></div>
    <div className="sticky top-16 z-20 -mx-4 mt-8 overflow-x-auto border-y bg-background/95 px-4 py-3 backdrop-blur sm:mx-0 sm:rounded-full sm:border"><div className="flex min-w-max gap-2"><button type="button" onClick={() => setCategory('all')} className={`rounded-full border px-4 py-2 text-sm font-semibold ${category === 'all' ? 'border-primary bg-primary text-primary-foreground' : ''}`}>All</button>{categories.map(c => <button type="button" key={c.id} onClick={() => setCategory(c.id)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${category === c.id ? 'border-primary bg-primary text-primary-foreground' : ''}`}>{c.name}</button>)}</div></div>
    <div className="mt-12 flex flex-col gap-16">{categories.filter((c) => category === 'all' || c.id === category).map(c => { const items = filtered.filter(item => item.category === c.id); return <section id={c.id} key={c.id} className="scroll-mt-32"><div className="mb-6 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black sm:text-3xl">{c.name}</h2><p className="mt-1 text-sm text-muted-foreground">{c.description}</p></div><div className="hidden h-14 w-20 overflow-hidden rounded-lg sm:block"><CategoryImage src={c.image} alt=""/></div></div>{items.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(item => { const count = cart[item.id] ?? 0; return <article key={item.id} className="flex items-start gap-4 rounded-2xl border bg-card p-4"><div className="min-w-0 flex-1"><div className="flex items-start gap-2"><h3 className="font-bold">{item.name}</h3>{item.vegetarian && <Leaf className="mt-1 size-4 shrink-0 text-primary" aria-label="Vegetarian"/>}</div><p className="mt-1 text-xs text-muted-foreground">{item.vegetarian ? 'Vegetarian · ' : ''}{item.available ? 'Available' : 'Currently unavailable'}</p><div className="mt-4 flex items-center gap-3"><p className="font-black text-primary">{formatPrice(item.price)}</p>{count === 0 ? <button type="button" onClick={() => updateCart(item, 1)} className="inline-flex items-center gap-1 rounded-full border px-3 py-1.5 text-xs font-bold hover:border-primary"><Plus size={14}/> Add</button> : <div className="flex items-center gap-2 rounded-full border px-1 py-1"><button type="button" onClick={() => updateCart(item, -1)} aria-label={`Remove one ${item.name}`} className="grid size-7 place-items-center rounded-full hover:bg-muted"><Minus size={14}/></button><span className="min-w-5 text-center text-sm font-bold">{count}</span><button type="button" onClick={() => updateCart(item, 1)} aria-label={`Add one ${item.name}`} className="grid size-7 place-items-center rounded-full hover:bg-muted"><Plus size={14}/></button></div>}</div></div></article>})}</div> : <p className="rounded-2xl border border-dashed p-6 text-sm text-muted-foreground">No dishes match your search in this category.</p>}</section> })}</div>
  </main></Shell>
}
